### ISSUE TITLE
Merging into dict from loop create new key 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#107]
Related to #66, when merging into a dict from a loop, we should be creating new keys. 

```yaml
resources:
  name: operator
  type: helm
  do some merge->: literal {'foo-{{index}}':'foo-{{index}}'} --for [1,2,3] --merge
```

Now creates:
```yaml
resources: 
  foo-2: foo-2
```

Which should be: 
```yaml
resources: 
  name: operator
  type: helm
  foo-0: foo-0
  foo-1: foo-1
  foo-2: foo-2
```

This is an edge case that practically has no purpose but should be accounted for.
