### ISSUE TITLE
Merge as arg messes up list 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#141]
This works 

```yaml
foo:
  - barr
  - ->: "{{item}}"
    merge: true
    for:
      - 1
      - 2
      - 5
```

This breaks:

```yaml
foo:
  - barr
  - ->: "{{item}}" --merge
    for:
      - 1
      - 2
      - 5
```

```
tackle.exceptions.TackleFileInitialParsingException: while parsing a block mapping
  in "/home/tackle-box/docs/scratch.yaml", line 806, column 5
expected <block end>, but found '<scalar>'
  in "/home/tackle-box/docs/scratch.yaml", line 806, column 19
```

Where 806 is the hook call
