### ISSUE TITLE
Support configuring function config 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#144]
We should support how a function deals with parameters and other APIs exposed by pydantic. 

For instance here, this will throw an error saying `extra fields not permitted`
```yaml
feature_type<-:
  status: TODO
  issue: ""


foo:
  status: ba
#  issue: baz
  bar: baz

f->: "{{feature_type(**foo)}}"
```
