### ISSUE TITLE
Support splat syntax for args / kwargs 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#149]
Would be good to support splat syntax. 

```yaml
class<-: 
  foo: str 

inputs: 
  foo: bar 

1->: "{{class(*inputs)}}"   
2->: class *inputs 
```

1 is supported already. 2 is not.
