### ISSUE TITLE
Support merging dict into top level 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#150]
This breaks inside `nested_set`:
```
do:
  ->: literal --merge
  for:
    - stuff
    - things
  input:
    foo: "{{item}}"
```

Would expect:

```
foo: things
```

Not very useful but when combined with a hook that outputs a dict it can produce interesting results.
