### ISSUE TITLE
Default fields are not validated in declarative hooks 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#152]
```
gen<-:
  all_languages:
    type: list
    default: foo 
```

This passes and it should error when the hook's field is assigned
