### ISSUE TITLE
`match` hook  with `block` + false `if` should set empty map 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#159]
In a match hook, when there is a matched block with a false if condition, the return should be an empty map. Right now iin this example we don't set any key (ie `matches_false` does not exist. 

```yaml
# This should exist in output as empty key
matches_false:
  ->: match matcher
  case:
    # This key should not exist
    bock_true->:
      if: false
      value: True
```
