### ISSUE TITLE
Determine if `match` hook should parse dictionaries by default 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#160]
Right now this does not parse the `literal` hook because dictionaries are passed by default. This should be determined if it is the right way to go as by default, blocks parse dicts which this should maybe do as well. 

```yaml
foo: bar

normal_dict_hook:
  ->: match foo
  case:
    bar:
      foo: foo
      stuff:
        ->: literal stuff
```
