### ISSUE TITLE
Allow extends to be a list

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#162]
Should allow this 

```yaml

greeter_base1<-:
  words:
    - hello
    - dude

greeter_base2<-:
  words:
    - hello
    - world

greeter_exec<-:
  extends:
    - greeter_base1
    - greeter_base2
  exec:
    p->: var {{item}} --for words
  return: p

t->: greeter_exec

```
