### ISSUE TITLE
kwags not usable in loop

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#166]
Right now kwargs are not usable in a loop: 

Here, item is not known. 

```yaml
foo<-:
  bar: baz

call:
  ->: foo --kwargs {{item}}
  for:
    - bar: bing
    - bar: bang
```

We need to move the kwargs handler to within the loop function
