### ISSUE TITLE
enum's are not qualified when set via command line 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#167]
running `tackle -pf yaml -z baz`

```yaml
<-:
  z:
    enum:
      - foo
      - bar

# result 
# z: baz
```

But it works fine internally:

```yaml
call->: func --z not-foo --try --except ok
```

Need to adjust how cli supplied params are imputed into context
