### ISSUE TITLE
Loops of map in declarative hook field bug

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#168]
This is splitting up the string `ordereddict([...` which should never happen 

```yaml
<-:
  field:
    k1: v1
    k2: v2
  call->: var "{{item}}" --for f
```
