### ISSUE TITLE
Private block hooks don't work with merge

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#173]
Per title, these don't work:

```yaml
that_>:
  merge: true
  key: foo
  value: foo

that:
  _>: block
  merge: true
  items:
    key: foo
    value: foo
```

```
.../env/lib/python3.10/site-packages/tackle-0.5.1-py3.10.egg/tackle/utils/dicts.py", line 140, in nested_get
    return element[keys[0]]
KeyError: 'that'
```

But these public hooks do: 

```yaml
that->:
  merge: true
  key: foo
  value: foo

that:
  ->: block
  merge: true
  items:
    key: foo
    value: foo
```
