### ISSUE TITLE
Clarify if references are preserved in context `update`

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#192]
Right now references are being preserved in the update hook. For instance 

```yaml
input_map:
  stuff: blah
  sturf: blu

dict_map:
  foo: bing
  bar: blu

update_map:
  ->: update
  src: "{{ input_map }}"
  input:
    stuff: "{{ dict_map }}"

update in place_>: update dict_map/foo bar
```

```python
def test_provider_system_hook_dicts_update_reference():
    """Show that references are preserved when updating a dict in place."""
    output = tackle('update-reference.yaml')
    assert output['update_map']['stuff']['foo'] == 'bar'
```

`foo` should be `bing`

So the way to fix this is if we copy the update. Only way.
