### ISSUE TITLE
`if` can't be used with when

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#216]
Per title

```yaml
expanded->:
  for:
    - foo
    - bar
  when: true
  if: item=='foo'
  do->: var item
```

Fails 

```python
def test_parser_conditionals_when_if():
    """Check `when` key is true with an `if` and loop."""
    output = tackle('when-if.yaml')

    assert len(output['expanded']) == 1
```

Length is 2... - if condition skipped
