### ISSUE TITLE
Support parameters such as `extra` in `model_config` within declarative hooks

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/tackle#219]
Currently we support the model_config from pydantic but having issue with the parser which does work on the model before instantiation where the model config is assessed. So for items such as `extra`, this currently does not work. 

```yaml
MyHook<-:
  foo: bar

  model_config:
    extra: allow

call->: MyHook --bar baz
```

But for other items such as 

```yaml
MyHook<-:
  foo: bar

  model_config:
    str_to_upper: true

call->: MyHook --foo baz
```

This does work (ie `BAZ`)
